defmodule NestGen2.NetworkTest do
  use ExUnit.Case, async: true
  alias NestGen2.Network

  test "nameservers skips loopback and IPv6 entries" do
    text = """
    # Generated by Connection Manager
    nameserver 127.0.0.1
    nameserver ::1
    nameserver 192.0.2.53
    """

    assert Network.nameservers(text) == [{192, 0, 2, 53}]
  end

  test "Nest's connman resolv.conf has no usable server" do
    assert Network.nameservers("nameserver 127.0.0.1\nnameserver ::1\n") == []
  end

  # Addresses from the documentation range (RFC 5737).
  test "default gateway from /proc/net/route (little-endian hex)" do
    route = """
    Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask
    wlan0\t010200C0\t00000000\t0005\t0\t0\t0\tFFFFFFFF
    wlan0\t350200C0\t010200C0\t0007\t0\t0\t0\tFFFFFFFF
    wlan0\t00000000\t010200C0\t0003\t0\t0\t0\t00000000
    """

    assert Network.default_gateway(route) == {192, 0, 2, 1}
  end

  test "no default route" do
    assert Network.default_gateway("Iface\tDestination\n") == nil
  end
end
