# /root/.bashrc on the Nest

case $- in *i*) ;; *) return ;; esac

# The bundled readline reads /etc/termcap; fall back to a known entry for
# terminals it doesn't list so line editing still works.
if ! grep -q "[|]${TERM}[|:]\|^${TERM}[|:]" /etc/termcap 2>/dev/null; then
  export TERM=xterm-256color
fi

HISTFILE=/root/.bash_history
HISTSIZE=5000
HISTFILESIZE=10000
HISTCONTROL=ignoreboth
HISTTIMEFORMAT='%F %T  '
shopt -s histappend checkwinsize cmdhist

# Append each command as it runs: this box reboots and hangs without warning,
# so history written only at logout would be lost.
PROMPT_COMMAND='history -a'

_badge='\[\e[1;38;5;16;48;5;208m\] NEST \[\e[0m\]'
_who='\[\e[1;38;5;208m\]\u@nest\[\e[0m\]'
_where='\[\e[1;38;5;75m\]\w\[\e[0m\]'
_char='\[\e[1;31m\]#\[\e[0m\]'
_title='\[\e]0;NEST \u@nest: \w\a\]'
PS1="${_title}${_badge} ${_who}:${_where}${_char} "
unset _badge _who _where _char _title

alias ll='ls -la'
alias la='ls -A'
alias logs='tail -n 30 /media/scratch/.nest_gen2_sdk/dial_control.log /media/scratch/.nest_gen2_sdk/watchdog.log'
alias erl='/media/scratch/.nest_gen2_sdk/otp/bin/erl'
alias iex='PATH=/media/scratch/.nest_gen2_sdk/otp/bin:$PATH /media/scratch/.nest_gen2_sdk/elixir/bin/iex'
